### PR TITLE
Updated SUSE distros

### PR DESCRIPTION
**Pull request by craigloewen-msft**
Validation is done in the GitHub action below.

### CODE REVIEW

**Comment by craigloewen-msft** [comment]
The pipeline caught my intentional bug :) Validating now

**Comment by sbradnick** [comment]
Could I trouble you to pull a refresh for SLE-15-SP5? It had a quarterly update in the time which we've been talking about this, then we should be 100% 1:1 with the Store - thanks!

```
        {
            "Name": "SUSE-Linux-Enterprise-15-SP5",
            "FriendlyName": "SUSE Linux Enterprise 15 SP5",
            "StoreAppId": "9N648JDGXK2D",
            "Amd64": true,
            "Arm64": false,
            "Amd64PackageUrl": "https://publicwsldistros.blob.core.windows.net/wsldistrostorage/SUSELinuxEnterprise15_SP5-231024.Appx",
            "Arm64PackageUrl": null,
            "PackageFamilyName": "46932SUSE.SUSELinuxEnterprise15SP5_022rs5jcyhyac"
        },
```

**Comment by craigloewen-msft** [comment]
@sbradnick wow that was fast! Yes of course, updated it. Thanks for the early heads up.

**Comment by craigloewen-msft** [comment]
@sbradnick please let me know if the PR content looks good as is. Once we get reviews from others on the WSL team we'll merge it.

**Review by benhillis — APPROVED** [review]

**Comment by craigloewen-msft** [comment]
@sbradnick I merged based off your earlier message, please let me know if you'd want any future changes! (email is best).

**Pull request merged**
