### PR TITLE
Richturn/edits

### PR DESCRIPTION
**Pull request by bitcrazed**
Added text & image asking users to file Console/UI/UX issues in Console repo.

### CODE REVIEW

**Comment by therealkenc** [comment]
You are probably aware of this utility already, but the heads up cost nothing. If the 251 issues marked console are migrated, it might help ease confusion about where people should post. On best evidence, not everyone reads the WSL CONTRIBUTING.md.

https://github.com/google/github-issue-mover
https://github-issue-mover.appspot.com/

**Comment by bitcrazed** [comment]
Yep, thanks. Intend on moving a bunch of Console asks over to the new repo, but am heads-down this week wrapping up some planning for the next cycle. Aim to move things around next week.

**Comment by benhillis** [comment]
Merging change. @bitcrazed let me know if you'd like a hand moving console-related issues over to the new GitHub.

**Comment by ahmedalishah31** [comment]
e05a895

**Pull request merged**
