### PR TITLE
Checkout enhancement feature to reach  bugs & instructions in Windows virtual environment to fix and organized 

### PR DESCRIPTION
**Pull request by djibal**
Update fly pull request in (Wpr-profile) WSL.

### CODE REVIEW

**Comment by djibal** [comment]
Looks good ☑️ to go

**Comment by bouseman** [comment]
Sorry. I understand nothing. What exactly I should to do?

**Comment by djibal** [comment]
Learn by example write down your purpose, What do you want to do to happen? @bouseman

**Review by djibal — COMMENTED** [review]
Correction of typing error in the script

**Review by djibal — COMMENTED** [review]
Reviewed me changes

**Review by djibal — COMMENTED** [review]
Update on the subject titres

**Pull request closed without merging**
