### PR TITLE
Update DistributionInfo.json

### PR DESCRIPTION
**Pull request by craigloewen-msft**
Updated Kali Linux's distribution info for this blob.

### CODE REVIEW

**Comment by craigloewen-msft** [comment]
@benhillis  since Pierre is OOF can you merge this if it looks good?

**Comment by OneBlue** [comment]
LGTM. Thanks Craig !

**Review by OneBlue — APPROVED** [review]

**Comment by craigloewen-msft** [comment]
@benhillis and @OneBlue I verified that this works on a virtual machine with this exact distribution file. Before and after version strings:

After:
Debian: 11 bullseye
Kali: 2022.3

Before:
Debian: 9 stretch
Kali:2019.2

**Review by benhillis — APPROVED** [review]
Looks good to me!

**Pull request merged**
