### PR TITLE
Updated SUSE 15

### PR DESCRIPTION
**Pull request by craigloewen-msft**
image

### CODE REVIEW

**Comment by sbradnick** [comment]
Will the Tumbleweed (X64 & ARM64) [updates](https://apps.microsoft.com/detail/9MSSK2ZXXN11) be included in a separate PR? Thanks!

**Comment by craigloewen-msft** [comment]
image

**Comment by craigloewen-msft** [comment]
@sbradnick yup!

**Comment by sbradnick** [comment]
> @sbradnick yup!

TY! Apologies if I was just being a bit too impatient :wink:

**Review by OneBlue — APPROVED** [review]

**Pull request merged**
