### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by I-Cat**
* add some windows command examples because most users are running Windows not linux to install WSL.

### CODE REVIEW

**Comment by djibal** [comment]
git add -m "add some Windowsesolution examples in :  command".git

**Comment by djibal** [comment]
Thank you TooGoodToGo!

**Comment by codedfile** [comment]
#5550

**Comment by codedfile** [comment]
From 36f321116839657a40d945ee30f3054ab69daee0 Mon Sep 17 00:00:00 2001
From: I-CAT <the_kat690@hotmail.com>
Date: Sat, 17 Apr 2021 21:20:55 -0400
Subject: [PATCH] Update CONTRIBUTING.md

---
 CONTRIBUTING.md | 24 ++++++++++++++++--------
 1 file changed, 16 insertions(+), 8 deletions(-)

diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index 7a73682..d0655f3 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -16,27 +16,35 @@ A title succinctly describing the issue.
 `Traceroute not working.`
 
 ### 2) Windows version / build number
-Your Windows build number.  This can be gathered from the CMD prompt using the `ver` command.
+Your Windows build number.  This can be gathered from the CMD prompt using the `cmd.exe --version` command.
 
-```
-C:\> ver
-Microsoft Windows [Version 10.0.14385]
+```cmd.exe
+C:\ cmd.exe --version
+Microsoft Windows [Version 10.0.21354.1]
 ```
 
-Note: The Windows Insider builds contain many updates and fixes. If you are running on the Creators Update (10.0.15063) please check to see if your issue has been resolved in a later build.  If you are running on the Anniversary Update (10.0.14393), please try updating to the Creators Update.
+Note: The Windows Insider builds contain many updates and fixes. If you are running on the Creators Update (10.0.15063) please check to see if your issue has been resolved in a later build.  If you are running on a Version below (10.0.14393), please try to update your Version.
 
 #### Example:
 
-`Microsoft Windows [Version 10.0.16170]`
+`Microsoft Windows [Version 10.0.21354.1]`
 
 ### 3) Steps required to reproduce
 
 Should include all packages and environmental variables as well as other required configuration.
 
-#### Example:
+#### Example: On linux 
 
 `$ sudo apt-get install traceroute && traceroute www.microsoft.com`
 
+#### Example: On Windows
+
+``
+`$ cmd.exe` 
+`CD C:\Windows\System32\`
+`tracert.exe`
+``
+
 ### 4) Copy of the terminal output
 
 #### Example:
@@ -178,4 +186,4 @@ Once the log collection is started, reproduce the problem, and run:
 $ wpr -stop wsl.etl
 ```
 
-This will stop the log collection and create a file named `wsl.etl` that will capture diagnostics information.
\ No newline at end of file
+This will stop the log collection and create a file named `wsl.etl` that will capture diagnostics information.

**Comment by codedfile** [comment]
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index 7a73682..d0655f3 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -16,27 +16,35 @@ A title succinctly describing the issue.
 `Traceroute not working.`
 
 ### 2) Windows version / build number
-Your Windows build number.  This can be gathered from the CMD prompt using the `ver` command.
+Your Windows build number.  This can be gathered from the CMD prompt using the `cmd.exe --version` command.
 
-```
-C:\> ver
-Microsoft Windows [Version 10.0.14385]
+```cmd.exe
+C:\ cmd.exe --version
+Microsoft Windows [Version 10.0.21354.1]
 ```
 
-Note: The Windows Insider builds contain many updates and fixes. If you are running on the Creators Update (10.0.15063) please check to see if your issue has been resolved in a later build.  If you are running on the Anniversary Update (10.0.14393), please try updating to the Creators Update.
+Note: The Windows Insider builds contain many updates and fixes. If you are running on the Creators Update (10.0.15063) please check to see if your issue has been resolved in a later build.  If you are running on a Version below (10.0.14393), please try to update your Version.
 
 #### Example:
 
-`Microsoft Windows [Version 10.0.16170]`
+`Microsoft Windows [Version 10.0.21354.1]`
 
 ### 3) Steps required to reproduce
 
 Should include all packages and environmental variables as well as other required configuration.
 
-#### Example:
+#### Example: On linux 
 
 `$ sudo apt-get install traceroute && traceroute www.microsoft.com`
 
+#### Example: On Windows
+
+``
+`$ cmd.exe` 
+`CD C:\Windows\System32\`
+`tracert.exe`
+``
+
 ### 4) Copy of the terminal output
 
 #### Example:
@@ -178,4 +186,4 @@ Once the log collection is started, reproduce the problem, and run:
 $ wpr -stop wsl.etl
 ```
 
-This will stop the log collection and create a file named `wsl.etl` that will capture diagnostics information.
\ No newline at end of file
+This will stop the log collection and create a file named `wsl.etl` that will capture diagnostics information.

**Comment by ahmedalishah31** [comment]
59491d3

**Pull request merged**
